[package]
name = "berline-gpui"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
gpui = {version = "0.2.1"}
chrono = { version = "0.4.42" }

serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"